updates/upgrades for hauler `v1.0.0`
rancherfederal/hauler-docs pull request #12
Opened 2024-02-18 17:38 UTC by zackbradys

### code related changes:
* Upgraded to `docusaurus v3`, specifically `docusaurus v3.1.1`
* Upgraded to `docusaurus-lunr-search` (from `docusaurus-search-local`) due to `docusaurus v3`
* Modified previous versions of the docs to support breaking changes in `docusaurus v3`

### docs related changes:
* Updated the docs to support new features and functionalities in `hauler v1.0.0`
* Updated existing pages in the docs based on feedback from users and recent demo
* Updated content in existing pages that have been "pending release"

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-02-18 21:43 UTC, zackbradys commented
Preview the updates here... http://54.235.23.85:3000/hauler-docs

2024-02-19 21:10 UTC, zackbradys commented
Preview site updated and ready for review!

2024-02-19 22:22 UTC, amartin120 requested changes

2024-02-19 22:22 UTC, amartin120 commented on docs/guides-references/hauler-content/charts.md
> +## Example Command for Images
```suggestion
## Example Commands for Charts
```

2024-02-19 22:22 UTC, amartin120 commented on docs/guides-references/hauler-content/files.md
> +## Example Command for Images
```suggestion
## Example Command for Files
```

2024-02-19 22:22 UTC, amartin120 commented on docs/guides-references/hauler-content/files.md
> +hauler store add file https://get.rke2.io
```suggestion
# local file
hauler store add file path/to/local/file.txt
```

2024-02-19 22:22 UTC, amartin120 commented on docs/guides-references/hauler-content/files.md
> +# fetch helm chart with specific version
```suggestion
# remote file with name
```

2024-02-19 22:42 UTC, amartin120 commented
Looks great!  Just a few suggestions.

2024-02-19 23:24 UTC, zackbradys commented
> Looks great! Just a few suggestions.

Updated and terminated the preview site.

2024-02-20 00:43 UTC, merged